services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_dev
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrongPassword123!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  api:
      container_name: api_dev
      build: 
        context: ./api
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
      depends_on:
        - sqlserver

  client:
    container_name: client_dev
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - api

volumes:
  sqlserver_data: